---
ID: "21a3008a-0f0e-4677-ac82-aff8416dddb5"
Parent: "64ee9778-10d3-492a-a52e-d229ce8b9fad"
Template: "64ee9778-10d3-492a-a52e-d229ce8b9fad"
Path: /sitecore/templates/CommerceConnect/Products/Specification Lookup/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{B95D069C-7867-4140-816D-6B204949B522}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130514T115200
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "f3f37114-38b0-43df-b9c7-512b62081bf1"
      Hint: Name
      Value: $name
