---
ID: "4faf3f74-b14a-4b9f-8d50-621146a20c7e"
Parent: "6e5fbb20-2d51-4b63-8563-65e6e8c61dfd"
Template: "6e5fbb20-2d51-4b63-8563-65e6e8c61dfd"
Path: /sitecore/templates/CommerceConnect/Products/Product Relations/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{93703013-77B6-48B5-8338-C29A5D15A1A6}"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130508T145249
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "62c925b2-b720-465b-8047-e776be22bd79"
      Hint: Description
      Value: $Name
