---
ID: "e0e2e091-86a4-44e6-b5f6-a9a92006e339"
Parent: "cf8fec2c-96fc-46c8-8a49-7bf908482f4b"
Template: "cf8fec2c-96fc-46c8-8a49-7bf908482f4b"
Path: /sitecore/templates/CommerceConnect/Products/Product ClassificationGroup/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{D5B1659A-83E7-485F-AD9A-555EECB564BF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130508T093757
    - ID: "44c7d49f-0c37-4a56-b135-aa831e7f1eb9"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
