---
ID: "9edc2147-808a-4ed0-a2b0-742d36a7a49c"
Parent: "fbca6069-d6c5-493e-83d7-c4a079e2717f"
Template: "fbca6069-d6c5-493e-83d7-c4a079e2717f"
Path: /sitecore/templates/CommerceConnect/Products/Product Resources/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{0D52EB5C-A153-4688-A217-151A17DE321E}"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130507T180431
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
